spring:
  cache:
    type: redis

  application:
    name: calculadoraapi

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5532/calculadora_db
    #username: huancho
    #password: 123
    #hikari:
    #  minimum-idle: 5
    #  maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    redis:
      #host: localhost
      host: redis
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /calculadora-api
external:
  porcentaje-service:
    url: http://localhost:8080/calculadora-api
springdoc:
  api-docs:
    enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"